# Generated by Django 3.2.25 on 2024-04-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usingsensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comm_test',
            new_name='user_action',
        ),
    ]
