# Generated by Django 3.2.25 on 2024-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingsensor', '0002_rename_comm_test_user_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='action_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
