# Generated by Django 3.2.25 on 2024-04-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingsensor', '0003_action_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_db',
            name='c_data',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action_db',
            name='x_data',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action_db',
            name='y_data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
