# Generated by Django 3.2.25 on 2024-04-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usingsensor', '0004_auto_20240429_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action_db',
            old_name='c_data',
            new_name='z_data',
        ),
    ]
