# Generated by Django 3.2.25 on 2024-04-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingsensor', '0005_rename_c_data_action_db_z_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_db',
            name='action',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='action_db',
            name='x_data',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='action_db',
            name='y_data',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='action_db',
            name='z_data',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
